project:
  type: website
  output-dir: _site

website:
  title: "torch-bench"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
